"""add teacher withdrawal payout details

Revision ID: 75364882518b
Revises: 0002_payment_phase1
Create Date: 2026-08-25 10:34:55.937851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75364882518b'
down_revision = '0002_payment_phase1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_profiles_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_longitude'), ['longitude'], unique=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_profiles_user_id'))
        batch_op.create_index(batch_op.f('ix_teacher_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_teacher_profiles_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_profiles_longitude'), ['longitude'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_index(batch_op.f('ix_users_mobile'))
        batch_op.create_index(batch_op.f('ix_users_mobile'), ['mobile'], unique=True)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_teacher_id'))
        batch_op.create_index(batch_op.f('ix_wallets_teacher_id'), ['teacher_id'], unique=True)

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_holder_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('upi_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('upi_id')
        batch_op.drop_column('account_holder_name')

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_teacher_id'))
        batch_op.create_index(batch_op.f('ix_wallets_teacher_id'), ['teacher_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_mobile'))
        batch_op.create_index(batch_op.f('ix_users_mobile'), ['mobile'], unique=False)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_profiles_longitude'))
        batch_op.drop_index(batch_op.f('ix_teacher_profiles_latitude'))
        batch_op.drop_index(batch_op.f('ix_teacher_profiles_user_id'))
        batch_op.create_index(batch_op.f('ix_teacher_profiles_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=False)

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_longitude'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_latitude'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
