"""add scheduling fields to hire requests

Revision ID: 835553e25b58
Revises: de07853611a2
Create Date: 2026-08-27 22:16:07.037928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835553e25b58'
down_revision = 'de07853611a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('class_duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teaching_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('travel_mode', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_hire_requests_scheduled_end'), ['scheduled_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_hire_requests_scheduled_start'), ['scheduled_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hire_requests_scheduled_start'))
        batch_op.drop_index(batch_op.f('ix_hire_requests_scheduled_end'))
        batch_op.drop_column('travel_mode')
        batch_op.drop_column('teaching_mode')
        batch_op.drop_column('class_duration_minutes')
        batch_op.drop_column('scheduled_end')
        batch_op.drop_column('scheduled_start')

    # ### end Alembic commands ###
