"""add smart class sessions and travel tracking

Revision ID: de07853611a2
Revises: 608f3a6795a5
Create Date: 2026-08-27 22:10:40.925331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de07853611a2'
down_revision = '608f3a6795a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('hire_request_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('actual_started_at', sa.DateTime(), nullable=True),
    sa.Column('actual_completed_at', sa.DateTime(), nullable=True),
    sa.Column('teaching_mode', sa.Enum('online', 'home', name='sessionteachingmode'), nullable=False),
    sa.Column('travel_mode', sa.Enum('walking', 'bike', 'car', 'online', name='travelmode'), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'travelling', 'arrived', 'in_progress', 'completed', 'cancelled', 'disputed', name='classsessionstatus'), nullable=False),
    sa.Column('attendance_status', sa.Enum('pending', 'present', 'absent', name='sessionattendancestatus'), nullable=False),
    sa.Column('origin_latitude', sa.Float(), nullable=True),
    sa.Column('origin_longitude', sa.Float(), nullable=True),
    sa.Column('destination_latitude', sa.Float(), nullable=True),
    sa.Column('destination_longitude', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_travel_minutes', sa.Integer(), nullable=True),
    sa.Column('travel_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('current_teacher_latitude', sa.Float(), nullable=True),
    sa.Column('current_teacher_longitude', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(), nullable=True),
    sa.Column('teacher_started_travel_at', sa.DateTime(), nullable=True),
    sa.Column('teacher_arrived_at', sa.DateTime(), nullable=True),
    sa.Column('timer_started_at', sa.DateTime(), nullable=True),
    sa.Column('timer_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('scheduled_end > scheduled_start', name='ck_class_session_valid_schedule'),
    sa.CheckConstraint('timer_duration_seconds > 0', name='ck_class_session_positive_timer'),
    sa.CheckConstraint('travel_buffer_minutes >= 0', name='ck_class_session_nonnegative_buffer'),
    sa.ForeignKeyConstraint(['hire_request_id'], ['hire_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_class_session_student_schedule', ['student_id', 'scheduled_start', 'scheduled_end'], unique=False)
        batch_op.create_index('ix_class_session_teacher_schedule', ['teacher_id', 'scheduled_start', 'scheduled_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_hire_request_id'), ['hire_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_scheduled_start'), ['scheduled_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_sessions_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_student_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_scheduled_start'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_hire_request_id'))
        batch_op.drop_index('ix_class_session_teacher_schedule')
        batch_op.drop_index('ix_class_session_student_schedule')

    op.drop_table('class_sessions')
    # ### end Alembic commands ###
